### ISSUE TITLE
Serves bind to local IP

### ISSUE THREAD

**Issue by agp8x** [uzh-bf/klicker-uzh#2549]
**Describe the bug**
When running with proper network isolation, the backend is not accessible.

**To Reproduce**
1. Use docker-compose default network
2. Add external network for proxy
3. Start setup
4. See error "Invalid character B in Json on Position 0" when trying to sign up

**Expected behavior**
Be able to sign up properly

**Additional context**
I'm not a node expert, so I guess the httpServer binds to the first IP. By passing an addition "0.0.0.0" into the [listen() call](https://github.com/uzh-bf/klicker-uzh/blob/dev/backend/src/server.js#L41) I was able to get a running setup with my traefik instance. A proper solution would be a configuration field to control this behaviour for regular use and docker setups.

We run many projects one one machine, so we need to keep the ports and networks clean. Each project is restricted as much as possbile to its local network. Only Public-facing services are included in the global proxy network, where a Traefik instance distributes the requests, adds TLS. So here the backend is in two networks: The proxy for requests, and the internal one to reach the databases.

**Comment by rschlaefli** [comment]
Hi @agp8x,

Thanks for the bug report. I have just pushed 1.6.2-alpha.0 with a new `APP_HOST` config variable for both the backend and frontend services (for consistency). The default `APP_HOST` is actually `0.0.0.0` for now (except in dev mode, where it always binds to `localhost`), as that seems a sane default in our Docker target deployment setting. I.e., so that we bind to all interfaces of networks that the container is a part of, if I understood your use case correctly.

Could you try whether that config value makes it work for your specific use case?

It might be very valuable if you could provide an excerpt of the Compose config for your use case using Traefik as a proxy (and with the described good network separation). I will add an example for Nginx to our Docker Compose deployment template, but have no experience with Traefik so far. Would that be possible? If yes, that would be great, you could just post it here (or PR).

Thanks a lot and best,
Roland

**Comment by agp8x** [comment]
Thanks for the quick reply, I'll test the update as soon as possible, and I will share my setup, already prepared the repo :)

Clemens

**Comment by agp8x** [comment]
Fixed with 1.6.2-alpha.0
